version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    docker:
      - image: cimg/node:20.19.0-browsers # Use a Node version matching your project
    steps:
      - checkout
      - browser-tools/install-chrome
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run test
      - run: npm run build
workflows:
  build_and_test:
    jobs:
      - build
